name: workflow_dispatch

on:
  workflow_dispatch:
    inputs:
      environment:
        description: this is env value where this workflow run
        default: dev
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  code:
    runs-on:
      - ubuntu-latest
    steps:
      - name: check git hub
        run: echo "hello code check"
  build:
    needs:
      - code
    runs-on:
      - ubuntu-latest
    steps:
      - name: build the image
        run: docker --version
  test:
    needs:
      - code
      - build
    runs-on:
      - ubuntu-latest
    steps:
      - name: test the code
        run: echo "check the code"
  dispach:
    needs:
      - code
      - build
      - test
    runs-on:
      - ubuntu-latest
    steps:
      - name: deploy to server
        run: uname -a

    
