# this will deploy the safe / secure / tested app to the prod-server
name: Deploy to server
on:
  workflow_call: 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: deploy with ssh to prod server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_SSH_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Updating packages"
            sudo apt-get update -y

            echo "Installing Docker and Compose"
            sudo apt-get install docker.io docker-compose-v2 -y

            echo "Starting and enabling Docker service"
            sudo systemctl start docker
            sudo systemctl enable docker

            echo "Adding user to docker group"
            sudo usermod -aG docker $USER
            newgrp docker

            echo "======== starting deployment ========"
            echo "======== Pull Latest Docker image ========="
            docker pull ${{ vars.DOCKERHUB_USER }}/github-action-app:latest
            echo "======== Stop and remove old container if running ========"
            docker stop github-action-app || true
            docker rm github-action-app || true
            echo "======== Run new container "
            docker run -d \
            -p 80:80 \
            --name github-action-app \
            ${{ vars.DOCKERHUB_USER }}/github-action-app:latest
            echo "Cleaning unused Docker images"
            docker image prune -f
            echo "======== Deployment completed ========"
