#you know we can forget and add API keys, Sensitive data, Credentials we can add this in pipelines and we can add this in secrets and we can use this in our pipelines or code and forget
#we will use Gitleaks for scanning git commits from own github and will find if any security vernability is there or not and we can add this in our pipelines and we can scan our code and find if any security vulnerability , api keys etc
name: Secrets Scan

on:
    workflow_call:


jobs: 
    secrets-scan:
        runs-on:
            - ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0 # Fetch all history for all branches and tags to ensure Gitleaks can scan the entire  commit history

            - name: Run Gitleaks scan
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication, GITHUB action manage it 
                

